# Generated by Django 4.2.30 on 2026-09-29 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllometricEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft (not usable for estimates)'), ('confirmed', 'Confirmed (locked when used)'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('form', models.CharField(default='agb = a * dbh_cm^b * height_m^c', help_text='Human-readable equation form.', max_length=64)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('dbh_min_cm', models.FloatField()),
                ('dbh_max_cm', models.FloatField()),
                ('height_required', models.BooleanField(default=True)),
                ('residual_sigma', models.FloatField(help_text='Multiplicative residual SD of ln(agb) [dimensionless].')),
                ('citation', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('measured_on', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['measured_on'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('x_m', models.FloatField(help_text='Plot centre X, projected CRS [m].')),
                ('y_m', models.FloatField(help_text='Plot centre Y, projected CRS [m].')),
                ('declared_area_ha', models.FloatField(help_text='Declared plot area in hectares. Plots may differ in size.')),
                ('boundary', models.JSONField(help_text='Boundary ring [[x_m, y_m], ...] in projected CRS.')),
                ('area_polygon_ha', models.FloatField(help_text='Polygon area in ha, computed at ingest and cross-checked.')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('family', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'species',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Stratum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('area_ha', models.FloatField(help_text='Known stratum land area in hectares (sampling frame).')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_field_number', models.CharField(max_length=16)),
                ('first_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trees_first', to='inventory.campaign')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trees', to='inventory.plot')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trees', to='inventory.species')),
                ('superseded_tree', models.ForeignKey(blank=True, help_text='Set when this row re-numbers an earlier tree (verified).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successors', to='inventory.tree')),
            ],
            options={
                'ordering': ['plot__code', 'current_field_number'],
            },
        ),
        migrations.CreateModel(
            name='TreeMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number_seen', models.CharField(help_text='Number physically on the tag at this campaign.', max_length=16)),
                ('x_m', models.FloatField(help_text='Stem position X, projected CRS [m].')),
                ('y_m', models.FloatField(help_text='Stem position Y, projected CRS [m].')),
                ('status', models.CharField(choices=[('alive_measured', 'Alive and remeasured'), ('alive_not_measured', 'Alive but not measured (missing data)'), ('dead', 'Dead (mortality observation)'), ('missing_tree', 'Tree not located')], max_length=20)),
                ('dbh_raw', models.FloatField(blank=True, null=True)),
                ('dbh_unit', models.CharField(blank=True, choices=[('cm', 'cm'), ('mm', 'mm'), ('in', 'in')], max_length=2, null=True)),
                ('dbh_cm', models.FloatField(blank=True, null=True)),
                ('height_raw', models.FloatField(blank=True, null=True)),
                ('height_unit', models.CharField(blank=True, choices=[('m', 'm')], max_length=2, null=True)),
                ('height_m', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=240)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='inventory.campaign')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='inventory.tree')),
            ],
            options={
                'ordering': ['tree__plot__code', 'tree__current_field_number'],
                'unique_together': {('tree', 'campaign')},
            },
        ),
        migrations.AddField(
            model_name='plot',
            name='stratum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='inventory.stratum'),
        ),
        migrations.CreateModel(
            name='MeasurementImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_payload', models.JSONField()),
                ('accepted', models.BooleanField()),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='inventory.campaign')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_rows', to='inventory.plot')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_number', models.CharField(max_length=16)),
                ('distance_m', models.FloatField(help_text='Distance between the two reported positions [m].')),
                ('status', models.CharField(choices=[('open', 'Unverified — excluded from estimates'), ('renumber', 'Verified renumber (same individual)'), ('distinct', 'Verified distinct individuals')], default='open', max_length=10)),
                ('resolution_note', models.CharField(blank=True, max_length=240)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.plot')),
                ('t1_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_t1', to='inventory.campaign')),
                ('t1_measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_t1', to='inventory.treemeasurement')),
                ('t2_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_t2', to='inventory.campaign')),
                ('t2_measurement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conflicts_as_t2', to='inventory.treemeasurement')),
            ],
            options={
                'ordering': ['plot__code', 'field_number'],
            },
        ),
        migrations.CreateModel(
            name='EstimateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft — recomputes with current data/equations'), ('confirmed', 'Confirmed — frozen, immutable'), ('superseded', 'Superseded by a newer confirmed version')], default='draft', max_length=12)),
                ('design_snapshot', models.JSONField(help_text='Stratum areas, expansion design, thresholds, CRS, uncertainty assumptions used for this run.')),
                ('result_payload', models.JSONField(blank=True, help_text='Full component breakdown + provenance + uncertainty.', null=True)),
                ('equation_checksum', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('equations', models.ManyToManyField(related_name='estimates', to='inventory.allometricequation')),
                ('t1_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_t1', to='inventory.campaign')),
                ('t2_campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_t2', to='inventory.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='allometricequation',
            name='species',
            field=models.ManyToManyField(related_name='equations', to='inventory.species'),
        ),
        migrations.AddIndex(
            model_name='tree',
            index=models.Index(fields=['plot', 'current_field_number'], name='inventory_t_plot_id_0838f9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='allometricequation',
            unique_together={('code', 'version')},
        ),
    ]
