# Generated by Django 4.2.30 on 2026-10-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('candidate', 'Candidate — proposed, awaiting validation'), ('validated', 'Validated — passed checks, reviewable'), ('approved', 'Approved — adopted as a new equation/version'), ('withdrawn', 'Withdrawn — retained for audit only')], default='candidate', max_length=12)),
                ('form', models.CharField(default='agb = a * dbh_cm^b * height_m^c', max_length=64)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('c', models.FloatField()),
                ('dbh_min_cm', models.FloatField()),
                ('dbh_max_cm', models.FloatField()),
                ('height_required', models.BooleanField(default=True)),
                ('residual_sigma', models.FloatField(help_text='Multiplicative residual SD of ln(agb) [dimensionless].')),
                ('citation', models.CharField(max_length=240)),
                ('validation_result', models.JSONField(blank=True, help_text='Structural/empirical check output of the validate action.', null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('species', models.ManyToManyField(related_name='candidate_equations', to='inventory.species')),
            ],
            options={
                'ordering': ['code', 'version'],
            },
        ),
        migrations.CreateModel(
            name='EquationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('open', 'Open — comparison available/awaiting decision'), ('approved', 'Approved — new EstimateVersion generated'), ('withdrawn', 'Withdrawn with the candidate — audit retained')], default='open', max_length=12)),
                ('coverage_status', models.CharField(choices=[('pending', 'No comparison run yet'), ('complete', 'Complete coverage — approval permitted'), ('incomplete', 'Incomplete — approval blocked')], default='pending', max_length=10)),
                ('lock_snapshot', models.JSONField(help_text='Frozen copy of the baseline frame: measurement rows, identity decisions, design snapshot and locked equations.')),
                ('lock_checksum', models.CharField(blank=True, max_length=64)),
                ('comparison', models.JSONField(blank=True, null=True)),
                ('compared_at', models.DateTimeField(blank=True, null=True)),
                ('candidate_checksum_at_comparison', models.CharField(blank=True, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adoption_reviews', to='inventory.estimateversion')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='inventory.equationcandidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=24)),
                ('actor', models.CharField(blank=True, default='station-console', max_length=80)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.equationreview')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewApprovalSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approval_slot', to='inventory.equationreview')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=24)),
                ('actor', models.CharField(blank=True, default='station-console', max_length=80)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.equationcandidate')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='generated_by_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_versions', to='inventory.equationreview'),
        ),
        migrations.AddIndex(
            model_name='equationreview',
            index=models.Index(fields=['status'], name='inventory_e_status_f15358_idx'),
        ),
        migrations.AddIndex(
            model_name='equationreview',
            index=models.Index(fields=['candidate', 'baseline_version'], name='inventory_e_candida_00a7fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equationcandidate',
            unique_together={('code', 'version')},
        ),
    ]
