# Generated by Django 4.2.30 on 2026-10-04 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquationAdoptionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('candidate', 'Candidate — under review'), ('validated', 'Validated — checks passed, awaiting decision'), ('approved', 'Approved — new estimate version generated'), ('withdrawn', 'Withdrawn — comparisons retained for audit')], default='candidate', max_length=12)),
                ('candidate_spec', models.JSONField(help_text='Candidate equation set: {species_code: {code, version, a, b, c, dbh_min_cm, dbh_max_cm, height_required, residual_sigma, citation, form}, ...}.')),
                ('species_scope', models.JSONField(default=list, help_text='Applicable species codes covered by the candidate.')),
                ('validation_payload', models.JSONField(blank=True, help_text='Structural/domain validation outcome (checks + coverage preview at validation time).', null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('created', 'Candidate created'), ('validated', 'Validation run'), ('compared', 'Impact comparison against a locked baseline'), ('approval_rejected', 'Approval attempted and rejected'), ('approved', 'Approved — new equation rows + estimate version'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('actor', models.CharField(blank=True, help_text='Reviewer / system actor.', max_length=80)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='inventory.equationadoptionreview')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReviewComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('complete', 'Complete — candidate fully covers the baseline'), ('incomplete', 'Incomplete — missing species or dbh class')], default='incomplete', max_length=12)),
                ('lock_fingerprints', models.JSONField(help_text='measurements / identity / frame / baseline-result hashes captured when the baseline was locked.')),
                ('coverage_matrix', models.JSONField(help_text='Per-species x dbh-class coverage: covered, missing species, out-of-range counts.')),
                ('difference_payload', models.JSONField(help_text='Tree-level, plot-level and population-level baseline vs candidate results, extrapolation and missing coverage.')),
                ('incomplete_reasons', models.JSONField(default=list, help_text='Human-readable reasons the comparison is not approvable.')),
                ('baseline_reproduced', models.BooleanField(help_text='Re-running the baseline equations reproduced the confirmed result byte-for-byte (no equation-independent drift).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baseline_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_comparisons', to='inventory.estimateversion')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparisons', to='inventory.equationadoptionreview')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='estimateversion',
            name='generated_by_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_version', to='inventory.equationadoptionreview'),
        ),
    ]
